region              =   "us-west-2"
identifier          =   "aurora-cluster"
engine              =   "aurora-postgresql"
engine_version      =   "11.7.postgresql_aurora.2.03.2"
name                =   "mydb"
username            =   "postgres"
password            =   "redhat2021"