project_id      =       "civil-celerity-239622"
display_name    =       "Snoop-dogg"
roles           =       "roles/container.admin"
cpath           =       "/home/murodbey/Terraform-projects/service-account-gcp/account.json"
region          =       "us-central1"  