cluster_name            =    "snoop-dogg"
node_count              =    "2"
cpath                   =    "/root/Terraform-project/Kube-cluster-deployment/service_account_key.json"
project                 =    "tough-country-240119"
region                  =    "us-central1"
node_name               =    "fuchicorp"