cluster_name            =    "snoop-dogg"
initial_node_count      =    "2"
cpath                   =    "/home/murodubechicago/Terraform-project/service_account_key.json"
project                 =    "civil-celerity-239622"
region                  =    "us-central1"